### ISSUE TITLE
WARNING: Confluence returned HTTP error 404 - NotFound

### ISSUE THREAD

**Issue by aslanovsergey** [AtlassianPS/ConfluencePS#100]
Hello,

I try to run cmdlets like Get-ConfluenceSpace and Get-ConfluencePage applying different params but always get error back 'WARNING: Confluence returned HTTP error 404 - NotFound'

Before i set environment with
Import-Module ConfluencePS
Set-ConfluenceInfo -BaseURI 'https://YourCloudWiki.atlassian.net' -PromptCredentials

PSVersion                      5.1.15063.674
I use last version of module: 2.1.0
Atlassian Confluence 5.3.3

**Comment by lipkau** [comment]
the atlassian cloud link for confluence always need the `.net/wiki/` suffix

**Comment by aslanovsergey** [comment]
Hello, 

It doesn't make any difference

my url look like this now: https://wiki.mycompanydomain.com:8443/wiki/

**Comment by lipkau** [comment]
Please give the full line that you are trying to run and the URL of the confluence start page (can be redacted)

**Comment by aslanovsergey** [comment]
So just downloaded latest version and restored date and now it works. I guess the reason was the server was a bit outdated. 5.3.3 (2014)
