### ISSUE TITLE
Text encoding problems

### ISSUE THREAD

**Issue by aslanovsergey** [AtlassianPS/ConfluencePS#101]
Hello

I have a problem with encoding while running Get-ConfluencePage for pages with russian text

I can see those pages normally from browser

But with Get-ConfluencePage I realized I get russian text in "iso-8859-1" encoding (Any properties: Title, Russian text in body an so on )

My Environment
Windows 2012 r2 64
ConfluencePS  2.1.0
PSVersion  5.1.15063.726
Confluence Server 6.5

**Comment by aslanovsergey** [comment]
Ok, for example there is a page and its title is: Схема СКУД
but i get PS C:\WINDOWS\system32> Get-ConfluencePage -PageID 10059922

ID         Status    Title                                SpaceKey        Version
--         ------    -----                                --------        -------
10059922   current   Ð¡ÑÐµÐ¼Ð° Ð¡ÐÐ£Ð                  space1  2

**Comment by lipkau** [comment]
seems to be a bug in powershell itself:
https://github.com/PowerShell/PowerShell/issues/5528

**Comment by lipkau** [comment]
Workaround:
```powershell
Invoke-WebRequest @parameter -OutFile somefile.txt
ConvertFrom-Json (Get-Content somefile.txt -Encoding UTF8 -raw)
