### ISSUE TITLE
Can't open contribute page

### ISSUE THREAD

**Issue by aslanovsergey** [AtlassianPS/ConfluencePS#104]
https://atlassianps.org/docs/Contributing.html

404

Page Not Found

Sorry, but the page you are looking for has not been found. Try checking the URL for error, then hit the refresh button on your browser or try found something else in my website.

Home

**Comment by lipkau** [comment]
Yes. This page was not yet written.

Are you looking to contribute?

**Comment by aslanovsergey** [comment]
Hello, yes i could help, I'm working in a project and use your module actively and sometimes want to extend it

**Comment by lipkau** [comment]
great!

this is the basic flow (_all code block assume to be execute in the same batch/powershell console in this order_):

1. Fork it @ https://github.com/AtlassianPS/ConfluencePS/fork
2. Clone your fork  
```
git clone https://github.com/<YOU>/ConfluencePS
cd ConfluencePS
```
3. Create your feature branch  
```
git checkout -b my-new-feature
```
4. make your changes (preferred editor: [VS Code](https://code.visualstudio.com/) )  
```
code .
```
5. Commit your changes  
```
git commit -am 'Add some feature'
```
6. Push to the branch  
```
git push origin my-new-feature
```
7. Create new Pull Request @ https://github.com/AtlassianPS/ConfluencePS/compare
