### ISSUE TITLE
Get-ConfluencePage -Title performance is impossibly slow

### ISSUE THREAD

**Issue by jimj13** [AtlassianPS/ConfluencePS#118]
### Expected Behavior
Calling Get-ConfluencePage -Title should quickly return the page.

### Current Behavior
Currently, it appears that because -Title requires -SpaceKey or -Space, all pages in the space are returned, and then filtered for title matching. With a space containing > 5K pages, this call (for a single page) will take over 18 minutes.

### Possible Solution
Rework to allow the Confluence API to do the heavy lifting rather than pulling down entire spaces for local filtering.

### Context
We use PowerShell to take large lists of items and produce documentation "stubs" in Confluence. The items have known title formulations. To do updates to the items, we need to query Confluence by the formulated title to retrieve the ID; the ID is then used with the update commands (Set-ConfluencePage or Remove-ConfluencePage).

### Your Environment
ConfluencePS 2.1.4
PSVersion                      5.0.10240.17709
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10011.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3

**Comment by lipkau** [comment]
This has already been implemented with #117.

But as this changes the behavior of -Title, it is a breaking change and is waiting for the release of v3.0

**Comment by lipkau** [comment]
In the mean time, I suggest using the new -CQL paramater
