### ISSUE TITLE
Credentials and URI do not cache when running inside another function

### ISSUE THREAD

**Issue by chosenv3** [AtlassianPS/ConfluencePS#141]
Hi Guys,

i am not sure if this is related to the module or if this is basic Powershell behavior however when I call 'set-confluenceinfo' from inside another function, it sets all the modules as expected (I can see this in vebose) but when my next command is then 'set-confluenceinfo' it prompts me for URi and Credentials.

If I run 'set-confluenceinfo' manually outside the function it works.

It is almost like it sets and then forgets.

Apart from this, is there a way to get it to use existing domain credentials? For example windows authentication instead of forcing me to provide creds?

P$ version = 5.1.14393.1944
ConfluencePS version = 2.3.6

Thanks,

Craig

**Comment by chosenv3** [comment]
hmm.. the only difference is that my function is compiled inside another module. I wonder if this is the cause?
I also create a credential object rather than prompting, not sure if that makes a difference?

Function below.

test {
[cmdletBinding()]
param
(
    $Username = "username",
    $Password = "Password",
    [int]$ParentID = '123456'
)

$secpasswd = ConvertTo-SecureString $Password -AsPlainText -Force
$mycreds = New-Object System.Management.Automation.PSCredential ($Username, $secpasswd)
$APIURI = "https://confluence"
set-confluenceinfo -BaseURI $APIURI -Credential $mycreds
Get-ConfluenceChildPage -apiURi $APIURI -Credential $mycreds -PageID $ParentID

}

**Comment by chosenv3** [comment]
When I run it your way I can get it to work too.

**Comment by lipkau** [comment]
I will do some more testing tomorrow... for now I have this:

![image](https://user-images.githubusercontent.com/4992870/40184259-0c625102-59f0-11e8-9666-65403e9dfe95.png)

**Comment by lipkau** [comment]
found it!

this is the code I tried and worked:

```powershell
New-Module -Name "test" -ScriptBlock {
    Import-Module ConfluencePS -Force
    function test {
        [cmdletBinding()]
        param
        (
            $Username = "admin",
            $Password = "11111111111"
        )

        $secpasswd = ConvertTo-SecureString $Password -AsPlainText -Force
        $mycreds = New-Object System.Management.Automation.PSCredential ($Username, $secpasswd)

        $APIURI = "https://powershell.atlassian.net/wiki"

        Set-ConfluenceInfo -BaseURI $APIURI -Credential $mycreds
        $PSDefaultParameterValues = $global:PSDefaultParameterValues
        
        Get-ConfluenceSpace -Credential $mycreds
    }
} | Import-Module
```

lets break it down:

* `$PSDefaultParameterValues = $global:PSDefaultParameterValues`: `Set-ConfluenceInfo` writes your settings into the global instance of `$PSDefaultParameterValues`. However, when you run a command inside the same function inside a module, this function does not use that scope. By adding this line, you set the local version of the `$PSDefaultParameterValues` to the same value as the global - and thus it works
* `Get-ConfluenceSpace -Credential $mycreds`: you still used the `-apiUri` parameter. please remove that, as the `Set-ConfluenceInfo` appends `/rest/api` to the base URL you provided. therefore using the same value in `set-confluenceinfo -BaseURI $APIURI` and `Get-ConfluenceChildPage -apiURi $APIURI` will fail
