### ISSUE TITLE
Extra trailing slash with -apiURi parameter

### ISSUE THREAD

**Issue by brianbunke** [AtlassianPS/ConfluencePS#153]
### Expected Behavior
Supplying a URI with no trailing slash to a specific command should work.
```posh
$Table | ConvertTo-ConfluenceStorageFormat -apiURi 'https://wiki.contoso.com' -Credential $Cred
```

### Current Behavior
An extra trailing slash is added, breaking the API call. Relevant snips:

```
DEBUG: [ConvertTo-ConfluenceStorageFormat] PSBoundParameters:
Key        Value
---        -----
apiURi     https://wiki.contoso.com/
```
```
DEBUG: [Invoke-Method] PSBoundParameters: 
Key        Value                                                                                                                                             
---        -----                                                                                                                                             
URi        https://wiki.contoso.com//contentbody/convert/storage
```

### Steps to Reproduce (for bugs)

```posh
Set-ConfluenceInfo -BaseURi 'https://wiki.contoso.com' -Credential $Cred
$Table = Get-ConfluenceSpace | ConvertTo-ConfluenceTable
# Specify the parameters here, in spite of already specifying above
$Table | ConvertTo-ConfluenceStorageFormat  -apiURi 'https://wiki.contoso.com' -Credential $Cred
```

### Workaround
Use `Set-ConfluenceInfo` at the top and do not specify `-apiURi` elsewhere.
```posh
Set-ConfluenceInfo -BaseURi 'https://wiki.contoso.com' -Credential $Cred
$wt = Get-ConfluenceSpace | ConvertTo-ConfluenceTable 
$wt | ConvertTo-ConfluenceStorageFormat
```
This works as expected, which makes this bug very low priority (in my use case).

### Context
Because the workaround is simple (for me), I have not investigated if this happens on all commands, or only in certain circumstances. Thought it was important to file the bug to get it on the record, anyway.

### Your Environment
ConfluencePS 2.3.6
PowerShell 5.1

**Comment by brianbunke** [comment]
Sorry 🙁 

```posh
Set-ConfluenceInfo -BaseURi 'https://wiki.contoso.com' -Credential (Get-Credential)
$table | ConvertTo-ConfluenceStorageFormat -apiURi 'https://wiki.contoso.com' -Credential (Get-Credential) -Verbose -Debug
```

```
Invoke-Method : An unknown error ocurred.
At [...]\Modules\ConfluencePS\2.4.0\ConfluencePS.psm1:242 char:14
+             (Invoke-Method @iwParameters).value
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (    
       ...true';
    
:String) [Invoke-Method], ArgumentException
    + FullyQualifiedErrorId : InvalidResponse.Status404,Invoke-Method
```

```
DEBUG: [Invoke-Method] PSBoundParameters: 
Key        Value
---        -----
URi        https://wiki.contoso.com//contentbody/convert/storage
```

```
VERBOSE: [Invoke-Method] Invoke-WebRequest with: 

Uri : https://wiki.contoso.com/contentbody/convert/storage
```

---

```posh
# Still works
Set-ConfluenceInfo -BaseURi 'https://wiki.contoso.com' -Credential (Get-Credential)
$table | ConvertTo-ConfluenceStorageFormat
```

**Comment by brianbunke** [comment]
The `PSBoundParameters` for `Invoke-Method` in both instances:

```posh
Set-ConfluenceInfo -BaseURi 'https://wiki.contoso.com' -Credential (Get-Credential)
$table | ConvertTo-ConfluenceStorageFormat -apiURi 'https://wiki.contoso.com' -Credential (Get-Credential) -Verbose -Debug
```

> ErrorAction     : Stop
> Headers         : {Accept-Charset, Accept}
> ContentType     : application/json; charset=utf-8
> Credential      : System.Management.Automation.PSCredential
> Method          : Post
> **Uri             : https://wiki.contoso.com/contentbody/convert/storage**
> Body            : {123, 13, 10, 32...}
> UseBasicParsing : True
> Verbose         : False

```posh
Set-ConfluenceInfo -BaseURi 'https://wiki.contoso.com' -Credential (Get-Credential)
$table | ConvertTo-ConfluenceStorageFormat -Verbose -Debug
```

> ErrorAction     : Stop
> Headers         : {Accept-Charset, Accept}
> ContentType     : application/json; charset=utf-8
> Credential      : System.Management.Automation.PSCredential
> Method          : Post
> **Uri             : https://wiki.contoso.com/rest/api/contentbody/convert/storage**
> Body            : {123, 13, 10, 32...}
> UseBasicParsing : True
> Verbose         : False

**Comment by lipkau** [comment]
The problem i the `rest/api` in the URi.
`Set-ConfluenceInfo` appends it to the BaseURi. But the `-ApiURi` parameter expects the URi to contain it.

_This behavior is already changed in the v3 branch_

**Comment by brianbunke** [comment]
Sounds good. Closing this as documented behavior/bug that we expect to make consistent in v3.
