### ISSUE TITLE
Invoke-Method : Authentication is required

### ISSUE THREAD

**Issue by svanen83** [AtlassianPS/ConfluencePS#169]
## Description

I am having problems with the ConfluencePS plugin. My script was working fine until two weeks ago when I started getting this error:

> ```powershell
> WARNING: Confluence returned HTTP error 401 - Unauthorized
> Invoke-Method : Authentication is required
> At C:\Users\msv\Documents\WindowsPowerShell\Modules\ConfluencePS\2.5.0\ConfluencePS.psm1:851 char:13
> + Invoke-Method @iwParameters
> + CategoryInfo          : InvalidResult: ({"statusCode":4...n is required"}:String) [Invoke-Method], ArgumentException
> + FullyQualifiedErrorId : InvalidResponse.Status401,Invoke-Method
> ```

## Steps To Reproduce
I am running these three commands to reproduce the error:

> ```powershell
> Import-Module ConfluencePS
> Set-ConfluenceInfo -BaseURi https://scalepoint.atlassian.net/wiki -PromptCredentials
> Get-ConfluenceSpace
> ```

I use a set of credentials that are Site Admin and I have tried logging in with the same credentials through the web interface and that works fine. However, using the commands above I get the before mentioned error.

I also tried not using Set-ConfluenceInfo and instead adding -ApiUri and -Credentials directly to the Get-ConfluenceSpace command, but that gave the same error.

## Please Help
Can anybody help me out? Did something change - or am I doing something wrong?

**Comment by lipkau** [comment]
Hi @svanen83 

That error is shown if the credentials you provided in the dialog generated by the `-PromptCredentials` are being rejected by the server.
The most common reasons:
1. wrong user name
2. wrong password
3. some sort of authentication (2 factor) requires you to use API Tokens

I imagine your case is the 3rd. This is documented here:
https://atlassianps.org/docs/JiraPS/about/authentication.html#api-token
Let me know if you need further help, or if this didn't help in your case.

**Comment by svanen83** [comment]
> Hi @svanen83
> That error is shown if the credentials you provided in the dialog generated by the -PromptCredentials are being rejected by the server.
> The most common reasons:
> 
> wrong user name
> wrong password
> some sort of authentication (2 factor) requires you to use API Tokens
> 
> I imagine your case is the 3rd. This is documented here:
> https://atlassianps.org/docs/JiraPS/about/authentication.html#api-token
> Let me know if you need further help, or if this didn't help in your case.

It worked - thank you.

I was using my user + pass and not the API token as pass.
