### ISSUE TITLE
Content Overflow when resizing window width. CSS bug

### ISSUE THREAD

**Issue by operator888** [AtlassianPS/ConfluencePS#179]
Using this version: Powered by Atlassian Confluence 7.1.0

When adjusting the window size to be half the width of my monitor or 1/3 for example, then the contents of the https://confluence.xxxxx.yy/users/viewmyprofile.action Page are being displayed outside of the page's boxed layout.
 

![Confluence CSS breaks bug report](https://user-images.githubusercontent.com/3840384/70060026-1659d680-15e2-11ea-8219-19055f3ab3a8.jpg)

**Comment by lipkau** [comment]
Hi @operator888 
this is not related to the Powershell Module `ConfluencePS`

**Comment by operator888** [comment]
Hi, im sorry for the mistake, and thank you @lipkau for correcting me. 
Somehow im dont find the single Confluence git repo, i only find 10's of other related with this. 
Could you please help me to the right repository? 
Thank you and sorry for the inconvenience.

**Comment by lipkau** [comment]
Confluence is not open source and has no repo on github.
You cen ask for help or report a bug here: https://support.atlassian.com/confluence-server/
