### ISSUE TITLE
ConvertTo-Space : Cannot create object of type "ConfluencePS.Space". Cannot convert value "29290657992" to type "System.Int32". Error: "Value was either too large or  too small for an Int32."

### ISSUE THREAD

**Issue by Sesha-Netwoven** [AtlassianPS/ConfluencePS#186]
we are trying to fetch the page details from all spaces in our testing environment using Confluence PowerShell commands and Get-ConfluencePage or Get-ConfluenceSpace is throwing an error saying

we went through the package "ConfluencePS.psm1" where it throwing an error. i have attached the powershell script where its throwing an error.
<img width="704" alt="ConfluencePSLongInt32ErrorInPackage" src="https://user-images.githubusercontent.com/75480401/101158674-1ad02980-3652-11eb-906b-e0f7ae5c2964.PNG">

=========================================
ConvertTo-Page : Cannot create object of type "ConfluencePS.Page". Cannot convert value "2155413513" to type "System.Int32". Error: "Value was either too large or too
small for an Int32."
At C:\Program Files\WindowsPowerShell\Modules\ConfluencePS\2.5.0\ConfluencePS.psm1:1070 char:43
+ $result | & $converter
+ ~~~~~~~~~~~~
+ CategoryInfo : InvalidArgument: (:) [ConvertTo-Page], RuntimeException
+ FullyQualifiedErrorId : ObjectCreationError,ConvertTo-Page

======================================================

**Comment by pinkylabs** [comment]
For my specific use case (uploading attachments, converting page and downloading/uploading page) I have fixed some of the Int32 types to Int64 types:

- in C# Page class
- in Get-Attachment.ps1
- Get-Page.ps1
- Set-Page.ps1

It worked for me, but it's obviously a mini quick-fix.

See ".patch" file against ConfluencePS v2.5.0 [0001-hotifx.patch.txt](https://github.com/AtlassianPS/ConfluencePS/files/5987291/0001-hotifx.patch.txt)

**Comment by lesterw1** [comment]
Can we get this pulled in and fixed please?  I am having the same issue with **Get-ConfluencePag**e and **Set-ConfluencePage**.
