### ISSUE TITLE
Get-ConfluencePage -Title string matching

### ISSUE THREAD

**Issue by brianbunke** [AtlassianPS/ConfluencePS#74]
Get-WikiPage (1.0) is not case sensitive, and performs wildcard matching. Get-ConfluencePage (`develop` branch) is case sensitive, and only returns exact matches.

This is because `Where-Object` was used before to be more forgiving, and the new version sends the string in the API call, which does not allow any of that behavior.

### Expected Behavior
PowerShell is case insensitive by default. Whenever it's reasonable, I like to mask API restrictions and allow this intuitive behavior.

### Current Behavior
You need to know the exact page name as proper case for `-Title` to return a result. This is pretty inconvenient, IMHO.

### Possible Solution
Instead of sending the string in the REST call, return the results from the REST call, and then perform a `Where-Object` against the page name.

### Steps to Reproduce (for bugs)
```posh
Get-WikiPage -Title test
Get-WikiPage -Title Test*
Get-WikiPage -Title 'Test Page'
Get-ConfluencePage -Title test
Get-ConfluencePage -Title Test*
Get-ConfluencePage -Title 'Test Page'
```

### Context
I understand my "possible solution" is inefficient, but I consider `-Title` mostly unusable without it. If you need to be perfect to return anything, you'd probably just use `-PageID` anyway.

### Your Environment
1.0.69 / `develop` branch (future 2.0)

**Comment by lipkau** [comment]
Ok. Will change it
