### ISSUE TITLE
Piping to Get-ConfluencePage

### ISSUE THREAD

**Issue by brianbunke** [AtlassianPS/ConfluencePS#75]
### Expected Behavior
Piping `[ConfluencePS.Space]` objects into `Get-ConfluencePage` should bind to the `-Space` parameter and filter page results accordingly.

### Current Behavior
I receive an error when attempting this.

### Steps to Reproduce (for bugs)
```posh
PS C:\> Get-ConfluenceSpace -SpaceKey KB | Get-ConfluencePage
WARNING: Confluence returned HTTP error 404 - NotFound
Invoke-Method : 
At [...]\ConfluencePS\Public\Get-Page.ps1:168 char:21
+                     Invoke-Method @iwParameters
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Method
```

### Your Environment
ConfluencePS `develop` branch, a689311e61c12de9de5ba5d4de9db3b44be9c58f

**Comment by lipkau** [comment]
The problem is this line:
https://github.com/AtlassianPS/ConfluencePS/blob/develop/ConfluencePS/Public/Get-Page.ps1#L19

by allowing the parameter to by piped by property name, which is ID, piping a Space object (which also includes the id property), it thinks the Space is the PageID.
We can:
* remove space from a valid pipe object
* make a new parameter `-PageObject` which will take the pipe from Page objects

**Comment by brianbunke** [comment]
Sorry, but would you please clarify your two suggestions?

- remove space from a valid pipe object
Meaning, no piping into this command?
- make a new parameter -PageObject which will take the pipe from Page objects
But we're trying to intake Space objects here?

**Comment by lipkau** [comment]
* yes: it will no longer be possible to pipe a `ConfluencePS.Space` object
* no. the new parameter would take the `ConfluencePS.Page` as input, thus not using `$PageID` (with alias `Id`) and allowing `-Space` to get `ConfluencePS.Space` object from the pipe

**Comment by brianbunke** [comment]
By changing this:

```posh
# Filter results by space object(s), typically from the pipeline
[Parameter(
    Mandatory = $true,
    ValueFromPipeline = $true,
    ParameterSetName = "bySpaceObject"
)]
[Parameter(
    ValueFromPipeline = $true,
    ParameterSetName = "byTitle"
)]
[Parameter(
    ValueFromPipeline = $true,
    ParameterSetName = "byLabel"
)]
[ConfluencePS.Space]$Space,
```

To this:

```posh
# Filter results by space object(s), typically from the pipeline
[Parameter(
    Mandatory = $true,
    ValueFromPipeline = $true,
    ValueFromPipelineByPropertyName = $true,
    ParameterSetName = "bySpaceObject"
)]
[Parameter(
    ValueFromPipeline = $true,
    ValueFromPipelineByPropertyName = $true,
    ParameterSetName = "byTitle"
)]
[Parameter(
    ValueFromPipeline = $true,
    ValueFromPipelineByPropertyName = $true,
    ParameterSetName = "byLabel"
)]
[ConfluencePS.Space]$Space,
```

The problem is fixed for me. We can clean things up, but at first glance, this appears to solve the issue without breaking PageID piping.

**Comment by lipkau** [comment]
That works indeed:
if more than one parameter can be bound from the pipeline by property name, the argument with the same type hint as the `$_` in the pipe will be preferred
