### ISSUE TITLE
Win 8.1 / PSv4 silently fails GET calls

### ISSUE THREAD

**Issue by brianbunke** [AtlassianPS/ConfluencePS#88]
On Windows 8.1, using PowerShell v4 and ConfluencePS 2.0.0, get calls silently drop all objects and return nothing. (Behavior not seen on Win10 / PS v5.1, and I haven't tested any other versions.)

### Expected Behavior
`Get-*` commands should return objects.

I can confirm this happens to `Get-Page` and `Get-Space`; I'll use `Get-Space` for my examples here.

### Current Behavior
Because `ConvertFrom-Json` returns a `[PSCustomObject]` type, private functions like `ConvertTo-Space` basically rely on this behavior:

```posh
([PSCustomObject]@{key = 'a'}) -as [ConfluencePS.Space]
```

This silently fails on Win8.1 / PSv4. If you rearrange the casting:

```posh
[ConfluencePS.Space]([PSCustomObject]@{key = 'a'})
```

> Cannot convert value "@{key=a}" to type "ConfluencePS.Space". Error: "Cannot convert the "@{key=a}" 
value of type "System.Management.Automation.PSCustomObject" to type "ConfluencePS.Space"."

### Possible Solution
Haven't researched yet. Documenting here for follow-up.

### Steps to Reproduce (for bugs)
`Get-ConfluenceSpace` / `Get-ConfluenceSpace -Verbose -Debug`

### Your Environment
ConfluencePS 2.0
PowerShell v4
Windows 8.1 Enterprise

**Comment by lipkau** [comment]
It appears as PoSh v4 has trouble casting PSCustomObjects...
https://stackoverflow.com/questions/38217736/why-does-casting-pscustomobjects-to-custom-type-with-datetime-in-powershell-fail

My suggestion is to have a private method `ConvertTo-CustomObject` that converts it PSCustomObject to Hashtable and then to the custom class

**Comment by fdo-ng** [comment]
Hi guys, Is this still an issue? I am running this on a Windows 2012 - PSversion 5.1.14409.1005. Installed ConfluencePS via PowerShell Gallery. I do the very basic Set-ConfluenceInfo the Get-ConfluenceSpace  and it return blank.. Did the -verbose and -debug and got message below.

-----------------
ERBOSE: [Invoke-Method] Function started
DEBUG: [Invoke-Method] ParameterSetName: __AllParameterSets
DEBUG: [Invoke-Method] PSBoundParameters: 
Key                                                                                 Value
---                                                                                 -----
First                                                                18446744073709551615
GetParameters                                                             {expand, limit}
Method                                                                                Get
Skip                                                                                    0
URi               https://wiki.net/rest/api/content/33001464/child/page
IncludeTotalCount                                                                   False
Credential                                      System.Management.Automation.PSCredential
OutputType                                                              ConfluencePS.Page

DEBUG: [Invoke-Method] Using $GetParameters: 
Name                           Value                                                                                                                     
----                           -----                                                                                                                     
expand                         space,version,body.storage,ancestors                                                                                      
limit                          25                                                                                                                        



VERBOSE: [ConvertTo-GetParameter] Making HTTP get parameter string out of a hashtable
VERBOSE: [Invoke-Method] Invoking method Get to URI https://wiki.net/rest/api/content/33001464/child/page?expand=space,version,body.stor
age,ancestors&limit=25
VERBOSE: [Invoke-Method] Invoke-WebRequest with: 

ErrorAction     : Stop
Headers         : {Accept-Charset, Accept}
ContentType     : application/json; charset=utf-8
Credential      : System.Management.Automation.PSCredential
Method          : Get
Uri             : https://wiki.net/rest/api/content/33001464/child/page?expand=space,version,body.storage,ancestors&limit=25
UseBasicParsing : True
Verbose         : False
VERBOSE: [Invoke-Method] Failed to get an answer from the server
DEBUG: [Invoke-Method] Executed WebRequest. Access $webResponse to see details
VERBOSE: [Invoke-Method] No Web result object was returned from. This is unusual!
VERBOSE: [Invoke-Method] Function ended
VERBOSE: [Get-ConfluenceChildPage] Function ended

**Comment by lipkau** [comment]
Hi @fdo-ng 

This issue has been fixed and closed.
Please create a new issue for reporting the problems you are having :-)
